### ISSUE TITLE
list instead of table

### ISSUE THREAD

**Issue by luca0071** [XRM-OSS/Xrm-Templating-Language#19]
would it be possible to have a list instead of a table to be used with a fetch? as alternative, it'd be good to give the fetch as input of another template to the "foreach" behavior.

**Comment by DigitalFlow** [comment]
Hi @luca0071,

This has been implemented in [v3.8.0](https://github.com/XRM-OSS/Xrm-Templating-Language/releases/tag/v3.8.0).
An example of how to use it can be found here:

https://github.com/XRM-OSS/Xrm-Templating-Language/blob/master/README.md#map

I hope it helps.

Kind Regards,
Florian
