### ISSUE TITLE
Rendering HTML Templates in Power Automate

### ISSUE THREAD

**Issue by alexmare93** [XRM-OSS/Xrm-Templating-Language#27]
Hi, 
I'm trying to render an HTML Template by calling the Oss_XTLApplyTemplate action and passing the required parameters:

![image](https://user-images.githubusercontent.com/57076004/98018968-7dd76200-1e01-11eb-8afa-cf4acd953268.png)

I need to call a static template by retrieving it above and passing its oss_html in the "template" action parameter.
I receive this error:

```
{
  "error": {
    "code": "0x80040224",
    "message": "An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute):  Xrm.Oss.XTL.Templating.XTLProcessor: System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type Xrm.Oss.XTL.Templating.ProcessorConfig. Encountered unexpected character 'X'."
  }
}
```

But I don't have any tag or char like that.

Could you please help me?

This is my HTML:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<!--[if gte mso 9]>
<xml>
  <o:OfficeDocumentSettings>
    <o:AllowPNG/>
    <o:PixelsPerInch>96</o:PixelsPerInch>
  </o:OfficeDocumentSettings>
</xml>
<![endif]-->
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="x-apple-disable-message-reformatting">
  <!--[if !mso]><!--><meta http-equiv="X-UA-Compatible" content="IE=edge"><!--<![endif]-->
  <title></title>
  
    <style type="text/css">
      a { color: #0000ee; text-decoration: underline; }
[owa] .u-row .u-col {
  display: table-cell;
  float: none !important;
  vertical-align: top;
}

.ie-container .u-row,
[owa] .u-row {
  width: 800px !important;
}

.ie-container .u-col-100,
[owa] .u-col-100 {
  width: 800px !important;
}


@media only screen and (min-width: 820px) {
  .u-row {
    width: 800px !important;
  }
  .u-row .u-col {
    vertical-align: top;
  }

  .u-row .u-col-100 {
    width: 800px !important;
  }

}

@media (max-width: 820px) {
  .u-row-container {
    max-width: 100% !important;
    padding-left: 0px !important;
    padding-right: 0px !important;
  }
  .u-row .u-col {
    min-width: 320px !important;
    max-width: 100% !important;
    display: block !important;
  }
  .u-row {
    width: calc(100% - 40px) !important;
  }
  .u-col {
    width: 100% !important;
  }
  .u-col > div {
    margin: 0 auto;
  }
  .no-stack .u-col {
    min-width: 0 !important;
    display: table-cell !important;
  }

  .no-stack .u-col-100 {
    width: 100% !important;
  }

}
body {
  margin: 0;
  padding: 0;
}

table,
tr,
td {
  vertical-align: top;
  border-collapse: collapse;
}

p {
  margin: 0;
}

.ie-container table,
.mso-container table {
  table-layout: fixed;
}

* {
  line-height: inherit;
}

a[x-apple-data-detectors='true'] {
  color: inherit !important;
  text-decoration: none !important;
}

.ExternalClass,
.ExternalClass p,
.ExternalClass span,
.ExternalClass font,
.ExternalClass td,
.ExternalClass div {
  line-height: 100%;
}

@media (max-width: 480px) {
  .hide-mobile {
    display: none !important;
    max-height: 0px;
    overflow: hidden;
  }
}

@media (min-width: 481px) {
  .hide-desktop {
    display: none !important;
    max-height: none !important;
  }
}
    </style>
  
  

</head>

<body class="clean-body" style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #ffffff">
  <!--[if IE]><div class="ie-container"><![endif]-->
  <!--[if mso]><div class="mso-container"><![endif]-->
  <table class="nl-container" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #ffffff;width:100%" cellpadding="0" cellspacing="0">
  <tbody>
  <tr style="vertical-align: top">
    <td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top">
    <!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td align="center" style="background-color: #ffffff;"><![endif]-->
    

<div class="u-row-container" style="padding: 10px;background-color: transparent">
  <div style="Margin: 0 auto;min-width: 320px;max-width: 800px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;" class="u-row">
    <div style="border-collapse: collapse;display: table;width: 100%;background-color: transparent;">
      <!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding: 10px;background-color: transparent;" align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:800px;"><tr style="background-color: transparent;"><![endif]-->
      
<!--[if (mso)|(IE)]><td align="center" width="800" style="width: 800px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;" valign="top"><![endif]-->
<div class="u-col u-col-100" style="max-width: 320px;min-width: 800px;display: table-cell;vertical-align: top;">
  <div style="width: 100% !important;">
  <!--[if (!mso)&(!IE)]><!--><div style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;"><!--<![endif]-->
  
<table id="u_content_image_1" class="u_content_image" style="font-family:arial,helvetica,sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;" align="left">
        
<table width="100%" cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td style="padding-right: 0px;padding-left: 0px;" align="center">
      
      <img align="center" border="0" src="https://s3.amazonaws.com/unroll-images-production/projects%2F0%2F1603445540855-gruppo-sapio-cmyk-corretto.gif" alt="Image" title="Image" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;width: 100%;max-width: 780px;" width="780" class="v-src-width v-src-max-width"/>
      
    </td>
  </tr>
</table>

      </td>
    </tr>
  </tbody>
</table>

  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->
  </div>
</div>
<!--[if (mso)|(IE)]></td><![endif]-->
      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->
    </div>
  </div>
</div>



<div class="u-row-container" style="padding: 0px;background-color: transparent">
  <div style="Margin: 0 auto;min-width: 320px;max-width: 800px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;" class="u-row">
    <div style="border-collapse: collapse;display: table;width: 100%;background-color: transparent;">
      <!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding: 0px;background-color: transparent;" align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:800px;"><tr style="background-color: transparent;"><![endif]-->
      
<!--[if (mso)|(IE)]><td align="center" width="800" style="width: 800px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;" valign="top"><![endif]-->
<div class="u-col u-col-100" style="max-width: 320px;min-width: 800px;display: table-cell;vertical-align: top;">
  <div style="width: 100% !important;">
  <!--[if (!mso)&(!IE)]><!--><div style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;"><!--<![endif]-->
  
<table id="u_content_text_1" class="u_content_text" style="font-family:arial,helvetica,sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;" align="left">
        
  <div class="v-text-align" style="color: #000000; line-height: 140%; text-align: left; word-wrap: break-word;">
    <p style="font-size: 14px; line-height: 140%;">Gentile ${{Value("ownerid")}},</p>
<p style="font-size: 14px; line-height: 140%;"><br />Di seguito si riportano le opportunit&agrave; in Suo possesso in scadenza:</p>
<p style="font-size: 14px; line-height: 140%;">&nbsp;</p>
<p style="font-size: 14px; line-height: 140%;">${{RecordTable ( Fetch ( "&lt;fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false' no-lock='true'&gt;&lt;entity name='opportunity'&gt;&lt;attribute name='opportunityid'/&gt;&lt;attribute name='name'/&gt;&lt;order attribute='name' descending='false'/&gt;&lt;filter type='and'&gt;&lt;condition attribute='statecode' operator='eq' value='0'/&gt;&lt;condition attribute='estimatedclosedate' operator='today'/&gt;&lt;/filter&gt;&lt;link-entity name='systemuser' from='systemuserid' to='owninguser' link-type='inner' alias='ac'&gt;&lt;filter type='and'&gt;&lt;condition attribute='systemuserid' operator='eq' value='{1}'/&gt;&lt;/filter&gt;&lt;/link-entity&gt;&lt;/entity&gt;&lt;/fetch&gt;", Array(Value ( "systemuserid" ) )), "systemuser", Array( "sap_typology:Tipologia","name:Argomento","customerid:Cliente Testata","sap_pdcid:PDC","sap_leadid:Lead","sap_totalquantity:Quantit&agrave; Totale","sap_customtotalamount:Valore Totale","estimatedclosedate:Data Chiusura Opportunit&agrave;" ), { addRecordUrl: true })}}</p>
<p style="font-size: 14px; line-height: 140%;">&nbsp;</p>
<p style="font-size: 14px; line-height: 140%;">Cordiali Saluti</p>
  </div>

      </td>
    </tr>
  </tbody>
</table>

  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->
  </div>
</div>
<!--[if (mso)|(IE)]></td><![endif]-->
      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->
    </div>
  </div>
</div>


    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->
    </td>
  </tr>
  </tbody>
  </table>
  <!--[if (mso)|(IE)]></div><![endif]-->
</body>

</html>
```

and this is my JSON:

`{"counters":{"u_column":3,"u_row":2,"u_content_image":1,"u_content_text":1},"body":{"rows":[{"cells":[1],"columns":[{"contents":[{"type":"image","values":{"containerPadding":"10px","_meta":{"htmlID":"u_content_image_1","htmlClassNames":"u_content_image"},"selectable":true,"draggable":true,"duplicatable":true,"deletable":true,"src":{"url":"https://s3.amazonaws.com/unroll-images-production/projects%2F0%2F1603445540855-gruppo-sapio-cmyk-corretto.gif","width":1000,"height":300},"textAlign":"center","altText":"Image","action":{"name":"web","values":{"href":"","target":"_blank"}},"hideDesktop":false,"hideMobile":false}}],"values":{"_meta":{"htmlID":"u_column_1","htmlClassNames":"u_column"}}}],"values":{"displayCondition":null,"columns":false,"backgroundColor":"","columnsBackgroundColor":"","backgroundImage":{"url":"","fullWidth":true,"repeat":false,"center":true,"cover":false},"padding":"10px","hideDesktop":false,"hideMobile":false,"noStackMobile":false,"_meta":{"htmlID":"u_row_1","htmlClassNames":"u_row"},"selectable":true,"draggable":true,"duplicatable":true,"deletable":true}},{"cells":[50],"columns":[{"contents":[{"type":"text","values":{"containerPadding":"10px","_meta":{"htmlID":"u_content_text_1","htmlClassNames":"u_content_text"},"selectable":true,"draggable":true,"duplicatable":true,"deletable":true,"color":"#000000","textAlign":"left","lineHeight":"140%","linkStyle":{"inherit":true,"linkColor":"#0000ee","linkHoverColor":"#0000ee","linkUnderline":true,"linkHoverUnderline":true},"hideDesktop":false,"hideMobile":false,"text":"<p style=\"font-size: 14px; line-height: 140%;\">Gentile ${{Value(\"ownerid\")}},</p>\n<p style=\"font-size: 14px; line-height: 140%;\"><br />Di seguito si riportano le opportunit&agrave; in Suo possesso in scadenza:</p>\n<p style=\"font-size: 14px; line-height: 140%;\">&nbsp;</p>\n<p style=\"font-size: 14px; line-height: 140%;\">${{RecordTable ( Fetch ( \"&lt;fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false' no-lock='true'&gt;&lt;entity name='opportunity'&gt;&lt;attribute name='opportunityid'/&gt;&lt;attribute name='name'/&gt;&lt;order attribute='name' descending='false'/&gt;&lt;filter type='and'&gt;&lt;condition attribute='statecode' operator='eq' value='0'/&gt;&lt;condition attribute='estimatedclosedate' operator='today'/&gt;&lt;/filter&gt;&lt;link-entity name='systemuser' from='systemuserid' to='owninguser' link-type='inner' alias='ac'&gt;&lt;filter type='and'&gt;&lt;condition attribute='systemuserid' operator='eq' value='{1}'/&gt;&lt;/filter&gt;&lt;/link-entity&gt;&lt;/entity&gt;&lt;/fetch&gt;\", Array(Value ( \"systemuserid\" ) )), \"systemuser\", Array( \"sap_typology:Tipologia\",\"name:Argomento\",\"customerid:Cliente Testata\",\"sap_pdcid:PDC\",\"sap_leadid:Lead\",\"sap_totalquantity:Quantit&agrave; Totale\",\"sap_customtotalamount:Valore Totale\",\"estimatedclosedate:Data Chiusura Opportunit&agrave;\" ), { addRecordUrl: true })}}</p>\n<p style=\"font-size: 14px; line-height: 140%;\">&nbsp;</p>\n<p style=\"font-size: 14px; line-height: 140%;\">Cordiali Saluti</p>"}}],"values":{"backgroundColor":"","padding":"0px","border":{},"_meta":{"htmlID":"u_column_2","htmlClassNames":"u_column"}}}],"values":{"displayCondition":null,"columns":false,"backgroundColor":"","columnsBackgroundColor":"","backgroundImage":{"url":"","fullWidth":true,"repeat":false,"center":true,"cover":false},"padding":"0px","hideDesktop":false,"hideMobile":false,"noStackMobile":false,"_meta":{"htmlID":"u_row_2","htmlClassNames":"u_row"},"selectable":true,"draggable":true,"duplicatable":true,"deletable":true}}],"values":{"backgroundColor":"#ffffff","backgroundImage":{"url":"","fullWidth":true,"repeat":false,"center":true,"cover":false},"contentWidth":"800px","fontFamily":{"label":"Arial","value":"arial,helvetica,sans-serif"},"preheaderText":"","linkStyle":{"body":true,"linkColor":"#0000ee","linkHoverColor":"#0000ee","linkUnderline":true,"linkHoverUnderline":true},"_meta":{"htmlID":"u_body","htmlClassNames":"u_body"}}},"schemaVersion":5}`

Thank you

**Comment by DigitalFlow** [comment]
Hi @alexmare93,

you don't have to call the custom action, it suffices to create an email record with either the HTML Template lookup or the HTML Template unique name set.
I created a tutorial on my blog, this might help you: https://xrmadventuretime.com/tutorials/creating-html-emails-from-d365-power-automate-flows/

Kind Regards,
Florian

**Comment by alexmare93** [comment]
Hi @DigitalFlow ,
Thank you for your reply.
Unfortunately, I cannot create physical email records in CRM, but I will use Outlook 365 Email Connector in Power Automate.
For that reason, I am unable to bind the HTML Template to some records and I need to call "universally" an HTML Template in order to rendering it by passing it the dynamic target and, later on, get the JsonOutput response to deserialize and put it inside the Outlook 365 email body.
I saw the article you posted me but I didn't find it that useful for my purpose.
Did you do something like I need?

Thank you,
Alessandro

**Comment by DigitalFlow** [comment]
Hi Alessandro,

Yes I did, although in JS: https://github.com/XRM-OSS/Xrm-Templating-Language/blob/master/src/web/Xrm.Oss.XTL.Editor/components/App.tsx#L155

```JSON
{
                    target: {
                        Id: this.state.selectedEntityId,
                        LogicalName: this.state.selectedEntityLogicalName
                    },
                    template: template
}
```

I guess in your case the issue is that your HTML contains double quotes, which breaks the JSON string. You might need to escape them, perhaps there is also a PowerAutomate function for constructing a JSON object?

Kind Regards,
Florian

**Comment by alexmare93** [comment]
Hi Florian,

I workarounded the problem by creating a lookup on the target entity and using the templateField parameter into the Json Input.
Another problem I'm facing is about addRecordUrl: when I put it inside my HTML Template, the entire RecordTable does not appear in my Email:

![image](https://user-images.githubusercontent.com/57076004/99071550-a22a0000-25b2-11eb-98a8-566ca5d6783e.png)

This is the HTML part from the action response:

```
  <div class="v-text-align" style="color: #000000; line-height: 140%; text-align: left; word-wrap: break-word;">
    <p style="font-size: 14px; line-height: 140%;">Gentile AdminCrm #,</p>
<p style="font-size: 14px; line-height: 140%;"><br />Di seguito si riportano le opportunità in Suo possesso in scadenza:</p>
<p style="font-size: 14px; line-height: 140%;"><br /></p>
<p style="font-size: 14px; line-height: 140%;"> </p>
<p style="font-size: 14px; line-height: 140%;">Cordiali Saluti</p>
  </div>
```

this is the faulting RecordTable:

`${{RecordTable ( Fetch ( "<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false' no-lock='true'><entity name='opportunity'><attribute name='opportunityid'/><attribute name='name'/><order attribute='name' descending='false'/><filter type='and'><condition attribute='statecode' operator='eq' value='0'/><condition attribute='estimatedclosedate' operator='today'/></filter><link-entity name='systemuser' from='systemuserid' to='owninguser' link-type='inner' alias='ac'><filter type='and'><condition attribute='systemuserid' operator='eq' value='{1}'/></filter></link-entity></entity></fetch>", Array(Value("systemuserid"))), "systemuser", Array( "sap_typology:Tipologia","name:Argomento","customerid:Cliente Testata","sap_pdcid:PDC","sap_leadid:Lead","sap_totalquantity:Quantità Totale","sap_customtotalamount:Valore Totale","estimatedclosedate:Data Chiusura Opportunità" ), {addRecordUrl:true})}}`

Once I remove it, the table renders:

![image](https://user-images.githubusercontent.com/57076004/99071620-c38aec00-25b2-11eb-9ac5-18713afa8daa.png)

This is the working RecordTable:

`${{RecordTable ( Fetch ( "<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false' no-lock='true'><entity name='opportunity'><attribute name='opportunityid'/><attribute name='name'/><order attribute='name' descending='false'/><filter type='and'><condition attribute='statecode' operator='eq' value='0'/><condition attribute='estimatedclosedate' operator='today'/></filter><link-entity name='systemuser' from='systemuserid' to='owninguser' link-type='inner' alias='ac'><filter type='and'><condition attribute='systemuserid' operator='eq' value='{1}'/></filter></link-entity></entity></fetch>", Array(Value("systemuserid"))), "systemuser", Array( "sap_typology:Tipologia","name:Argomento","customerid:Cliente Testata","sap_pdcid:PDC","sap_leadid:Lead","sap_totalquantity:Quantità Totale","sap_customtotalamount:Valore Totale","estimatedclosedate:Data Chiusura Opportunità"), true)}}`

Do you know why?

Thank you,
Alessandro

**Comment by DigitalFlow** [comment]
Hi @alexmare93,

good job on finding a workaround!

Yes, when you use the record url it is expected that the organizationUrl is passed.
By default the XTL editor takes care of passing this inside the unsecureConfiguration of the plugin step.

But as you are using the custom action directly, you would either have to extend the payload where you are passing the templateField parameter to also pass the organizationUrl, so that it looks somewhat like this:
```JSON
 {
     "organizationUrl": "https://yoururl",
     "template": "...",
     "templateField": "..."
}
```

**Comment by DigitalFlow** [comment]
Hi @alexmare93,

any news on this?

Kind Regards,
Florian

**Comment by alexmare93** [comment]
Hi Florian,

Unfortunately, I was able to workaround that issue, but on the other side I need to retrieve a generic HTML Template and not to bind it to a lookup field.
I’m trying to figure out how to escape double quotes in HTML generated.

ALESSANDRO MARENGHI   |  Dynamics 365 (CE+CS+FS) Developer

T +39 347 5937193 | alessandro.marenghi@porini.it<mailto:alessandro.marenghi@porini.it>

[logo-dgs-porini-1]<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.porini.it%2F&data=02%7C01%7Calessandro.marenghi%40porini.it%7Cbe054de5d8374572116508d7e5c8f78a%7Cb3bce17afac9410ab1b532bbd3e015f5%7C0%7C0%7C637230523622681409&sdata=t13GwoW9AK21aqseiQm%2BMnarEyXbfXKZm7eqteRmG%2B0%3D&reserved=0>

[cid:image005.png@01D6C4A3.C6B0B0B0][cid:image006.png@01D6C4A3.C6B0B0B0]

CONFIDENTIALITY NOTICE: This message and its attachments (if any) may contain confidential, proprietary or legally privileged information and is intended only for the use of the addressee named above. No confidentiality or privilege is waived or lost by any mistransmission. If you are not the intended recipient of this message you are hereby notified that you must not use, disseminate, copy it in any form or take any action in reliance on it. If you have received this message in error please delete it and any copies of it and kindly inform the sender of this e-mail.

**Comment by DigitalFlow** [comment]
Hi @alexmare93,

are you still having issues with this? Can I help you in any way?

Kind Regards,
Florian

**Comment by alexmare93** [comment]
Hi @Florian Krönert<mailto:notifications@github.com>,

No, I found another workaround to achieve my goal.
Thank you anyway.

Best Regards,

ALESSANDRO MARENGHI   |  Dynamics 365 (CE+CS+FS) Developer

T +39 347 5937193 | alessandro.marenghi@porini.it<mailto:alessandro.marenghi@porini.it>

[logo-dgs-porini-1]<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.porini.it%2F&data=02%7C01%7Calessandro.marenghi%40porini.it%7Cbe054de5d8374572116508d7e5c8f78a%7Cb3bce17afac9410ab1b532bbd3e015f5%7C0%7C0%7C637230523622681409&sdata=t13GwoW9AK21aqseiQm%2BMnarEyXbfXKZm7eqteRmG%2B0%3D&reserved=0>

[cid:image005.png@01D6E7F9.7B189590][cid:image006.png@01D6E7F9.7B189590]

CONFIDENTIALITY NOTICE: This message and its attachments (if any) may contain confidential, proprietary or legally privileged information and is intended only for the use of the addressee named above. No confidentiality or privilege is waived or lost by any mistransmission. If you are not the intended recipient of this message you are hereby notified that you must not use, disseminate, copy it in any form or take any action in reliance on it. If you have received this message in error please delete it and any copies of it and kindly inform the sender of this e-mail.

**Comment by DigitalFlow** [comment]
Alright, so were you able to use XTL inside your PowerAutomate steps then?
Or did you have to abandon it?

**Comment by alexmare93** [comment]
Hi Florian,

Sorry for the delay in response.
I did another workaround: I created a CWA run by Power Automate. Inside the CWA, I'm creating an Email record with the HTML Template lookup field, so that it could retrieve HTML and render it.

Thank you anyway for your support,


ALESSANDRO MARENGHI   |  Dynamics 365 (CE+CS+FS) Developer

T +39 347 5937193 | alessandro.marenghi@porini.it<mailto:alessandro.marenghi@porini.it>

[logo-dgs-porini-1]<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.porini.it%2F&data=02%7C01%7Calessandro.marenghi%40porini.it%7Cbe054de5d8374572116508d7e5c8f78a%7Cb3bce17afac9410ab1b532bbd3e015f5%7C0%7C0%7C637230523622681409&sdata=t13GwoW9AK21aqseiQm%2BMnarEyXbfXKZm7eqteRmG%2B0%3D&reserved=0>

[cid:image005.png@01D6F0B6.AA9146D0][cid:image006.png@01D6F0B6.AA9146D0]

CONFIDENTIALITY NOTICE: This message and its attachments (if any) may contain confidential, proprietary or legally privileged information and is intended only for the use of the addressee named above. No confidentiality or privilege is waived or lost by any mistransmission. If you are not the intended recipient of this message you are hereby notified that you must not use, disseminate, copy it in any form or take any action in reliance on it. If you have received this message in error please delete it and any copies of it and kindly inform the sender of this e-mail.
