### ISSUE TITLE
RecordUrl with D365CE v9 not working

### ISSUE THREAD

**Issue by AlessandroBrusamolino** [XRM-OSS/Xrm-Templating-Language#30]
Hi,

If I put this command in preview using Solution Configuration works:
${{RecordUrl(Value("regardingobjectid.sap_ticketid"))})}}

When I put same command in HTML Template after render in my email token is replaced with blank.

Can you give me support please?

**Comment by DigitalFlow** [comment]
Hi @AlessandroBrusamolino,

organizationUrl is probably missing in the step. It is saved in the secure configuration, so it's not transported.

Can you please try the following: Open the Xrm-Templating-Solution (in the old UI, not powerapps), go to the Configuration page and click the Buttons "Manage SDK Steps".

For every step that contains something like "Apply XTL placeholders", select it, click ok and when it is loaded, just click the save button without changing anything.

That should "revive" the URLs. This is just needed once after installing the solution.

This is what is meant by the remark in the [RecordUrl function description](https://github.com/XRM-OSS/Xrm-Templating-Language#recordurl).

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @AlessandroBrusamolino,

any feedback on this? I'll close this issue, my previous suggestion should solve your issue.
If any problems remain, please reopen.

Kind Regards,
Florian

**Comment by alexmare93** [comment]
Hi @DigitalFlow,

Even trying with that, the URL doesn't appear. We tried also to build the link and adding dynamically only the id, but it seems to disappears: 
What I insert into the HTML Template: https://orgCRM.crm4.dynamics.com/main.aspx?etn=sap_tender&pagetype=entityrecord&id=%7B${{Value("regardingobjectid.sap_tenderid)}}%7D
What it renders: https://orgCRM.crm4.dynamics.com/main.aspx?etn=sap_tender&pagetype=entityrecord&id=%7B%7D

Thank you,
Regards
