### ISSUE TITLE
Need solution files for 9.1 on-premise

### ISSUE THREAD

**Issue by fvakiliev** [XRM-OSS/Xrm-Templating-Language#61]
Dear Florian!
Please upload the latest solution files for on-premise aka *_target_CRM_8.0_managet.zip.
Both of XrmOssXrmHtmlTemplating and XrmOssXrmTemplatingLanguage.
I really need it!

Thanks,
OldCat

**Comment by DigitalFlow** [comment]
Hi @fvakiliev,

sorry for the late response, the latest release has CRM_8.0 solutions, you can find them here: https://github.com/XRM-OSS/Xrm-Templating-Language/releases/tag/v3.9.6

Kind regards,
Florian
